// <auto-generated />
using System;
using Katuwang.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Katuwang.Migrations.Katuwang
{
    [DbContext(typeof(KatuwangContext))]
    [Migration("20220829151703_InitializeDB")]
    partial class InitializeDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Katuwang.Models.Masterlist", b =>
                {
                    b.Property<int>("entryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("baptismdate")
                        .HasColumnType("date");

                    b.Property<string>("barangay")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("datetime");

                    b.Property<string>("civilstatus")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("contactnum")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("createby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime");

                    b.Property<string>("entrynum")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("fathersname")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("firstdistrito")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("firstlokal")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("gender")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("givenname")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("grupo")
                        .HasColumnType("int");

                    b.Property<string>("idnum")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("isactive")
                        .HasColumnType("int");

                    b.Property<int>("isdeleted")
                        .HasColumnType("int");

                    b.Property<string>("minister")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("modifiedby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("modifieddate")
                        .HasColumnType("date");

                    b.Property<string>("mothersname")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("newgrupo")
                        .HasColumnType("int");

                    b.Property<int>("newpurok")
                        .HasColumnType("int");

                    b.Property<string>("organization")
                        .HasColumnType("varchar(6)");

                    b.Property<int>("purok")
                        .HasColumnType("int");

                    b.Property<string>("registrynum")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("relasyon")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("remarks1")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("remarks2")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("remarks3")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("sambahayan")
                        .HasColumnType("int");

                    b.Property<string>("spouse")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("spousename")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("suffix")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("weddingdate")
                        .HasColumnType("datetime");

                    b.HasKey("entryid");

                    b.ToTable("Masterlist");
                });
#pragma warning restore 612, 618
        }
    }
}
