// <auto-generated />
using System;
using Katuwang.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Katuwang.Migrations.Katuwang
{
    [DbContext(typeof(KatuwangContext))]
    partial class KatuwangContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Katuwang.Models.AttendanceWeekly", b =>
                {
                    b.Property<int>("entryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("createby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime");

                    b.Property<int>("destinadoid")
                        .HasColumnType("int");

                    b.Property<int>("grupo")
                        .HasColumnType("int");

                    b.Property<int>("isdeleted")
                        .HasColumnType("int");

                    b.Property<string>("modifiedby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("modifieddate")
                        .HasColumnType("date");

                    b.Property<decimal>("porsyento")
                        .HasColumnType("decimal");

                    b.Property<int>("purok")
                        .HasColumnType("int");

                    b.Property<int>("serialnumber")
                        .HasColumnType("int");

                    b.Property<int>("weeknum")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("entryid");

                    b.ToTable("AttendanceWeekly");
                });

            modelBuilder.Entity("Katuwang.Models.Destinado", b =>
                {
                    b.Property<int>("entryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("assignednum")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("createby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("entrydate")
                        .HasColumnType("datetime");

                    b.Property<string>("fathersname")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("givenname")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("grupoend")
                        .HasColumnType("int");

                    b.Property<int>("grupostart")
                        .HasColumnType("int");

                    b.Property<int>("isactive")
                        .HasColumnType("int");

                    b.Property<int>("isdeleted")
                        .HasColumnType("int");

                    b.Property<string>("modifiedby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("modifieddate")
                        .HasColumnType("date");

                    b.Property<string>("mothersname")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("purok")
                        .HasColumnType("int");

                    b.Property<string>("remarks1")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("remarks2")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("remarks3")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("suffix")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("type")
                        .HasColumnType("varchar(20)");

                    b.HasKey("entryid");

                    b.ToTable("Destinado");
                });

            modelBuilder.Entity("Katuwang.Models.Masterlist", b =>
                {
                    b.Property<int>("entryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("baptismdate")
                        .HasColumnType("date");

                    b.Property<string>("barangay")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("datetime");

                    b.Property<string>("civilstatus")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("contactnum")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("createby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime");

                    b.Property<string>("entrynum")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("fathersname")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("firstdistrito")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("firstlokal")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("gender")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("givenname")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("grupo")
                        .HasColumnType("int");

                    b.Property<string>("idnum")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("isactive")
                        .HasColumnType("int");

                    b.Property<int>("isdeleted")
                        .HasColumnType("int");

                    b.Property<int>("isupdated")
                        .HasColumnType("int");

                    b.Property<string>("minister")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("modifiedby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("modifieddate")
                        .HasColumnType("date");

                    b.Property<string>("mothersname")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("newgrupo")
                        .HasColumnType("int");

                    b.Property<int>("newpurok")
                        .HasColumnType("int");

                    b.Property<string>("organization")
                        .HasColumnType("varchar(6)");

                    b.Property<int>("purok")
                        .HasColumnType("int");

                    b.Property<string>("registrynum")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("relasyon")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("remarks1")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("remarks2")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("remarks3")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("sambahayan")
                        .HasColumnType("int");

                    b.Property<string>("spouse")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("spousename")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("suffix")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("weddingdate")
                        .HasColumnType("datetime");

                    b.HasKey("entryid");

                    b.ToTable("Masterlist");
                });

            modelBuilder.Entity("Katuwang.Models.Maytungkulin", b =>
                {
                    b.Property<int>("entryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("createby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime");

                    b.Property<string>("duty")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("entrydate")
                        .HasColumnType("datetime");

                    b.Property<int>("isactive")
                        .HasColumnType("int");

                    b.Property<int>("isdeleted")
                        .HasColumnType("int");

                    b.Property<string>("level")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("masterlistid")
                        .HasColumnType("int");

                    b.Property<string>("modifiedby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("modifieddate")
                        .HasColumnType("date");

                    b.Property<string>("remarks1")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("remarks2")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("remarks3")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("section")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("task")
                        .HasColumnType("varchar(100)");

                    b.HasKey("entryid");

                    b.HasIndex("masterlistid");

                    b.ToTable("Maytungkulin");
                });

            modelBuilder.Entity("Katuwang.Models.R401", b =>
                {
                    b.Property<int>("entryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("createby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime");

                    b.Property<int>("destinadoid")
                        .HasColumnType("int");

                    b.Property<DateTime>("entrydate")
                        .HasColumnType("datetime");

                    b.Property<int>("isdeleted")
                        .HasColumnType("int");

                    b.Property<int>("ismk")
                        .HasColumnType("int");

                    b.Property<int>("masterlistid")
                        .HasColumnType("int");

                    b.Property<string>("modifiedby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("modifieddate")
                        .HasColumnType("date");

                    b.Property<string>("month")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("remarks1")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("remarks2")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("remarks3")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("status")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("entryid");

                    b.HasIndex("masterlistid");

                    b.ToTable("R401");
                });

            modelBuilder.Entity("Katuwang.Models.SystemParameter", b =>
                {
                    b.Property<int>("entryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("createby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime");

                    b.Property<string>("description")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("group")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("isdeleted")
                        .HasColumnType("int");

                    b.Property<string>("level")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("modifiedby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("modifieddate")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("value")
                        .HasColumnType("varchar(100)");

                    b.HasKey("entryid");

                    b.ToTable("SystemParameter");
                });

            modelBuilder.Entity("Katuwang.Models.Transfer", b =>
                {
                    b.Property<int>("entryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("code")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("createby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime");

                    b.Property<string>("dcode")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("distrito")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("isdeleted")
                        .HasColumnType("int");

                    b.Property<int>("isletter")
                        .HasColumnType("int");

                    b.Property<string>("lcode")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("lokal")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("masterlistid")
                        .HasColumnType("int");

                    b.Property<string>("modifiedby")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("modifieddate")
                        .HasColumnType("date");

                    b.Property<int>("secretariatid")
                        .HasColumnType("int");

                    b.Property<DateTime>("transferdate")
                        .HasColumnType("datetime");

                    b.Property<int>("weeknum")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("entryid");

                    b.HasIndex("masterlistid");

                    b.ToTable("Transfer");
                });

            modelBuilder.Entity("Katuwang.Models.Maytungkulin", b =>
                {
                    b.HasOne("Katuwang.Models.Masterlist", "Masterlist")
                        .WithMany()
                        .HasForeignKey("masterlistid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masterlist");
                });

            modelBuilder.Entity("Katuwang.Models.R401", b =>
                {
                    b.HasOne("Katuwang.Models.Masterlist", "Masterlist")
                        .WithMany()
                        .HasForeignKey("masterlistid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masterlist");
                });

            modelBuilder.Entity("Katuwang.Models.Transfer", b =>
                {
                    b.HasOne("Katuwang.Models.Masterlist", "Masterlist")
                        .WithMany()
                        .HasForeignKey("masterlistid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masterlist");
                });
#pragma warning restore 612, 618
        }
    }
}
